' Module: Form_frm_1_Organizing
' Type: Document Module

Option Compare Database

Private Sub Command65_Click()
DoCmd.OpenForm "frm_Log_Change"
End Sub

Private Sub Command66_Click()
DoCmd.OpenForm "frm_Log_Decision"
End Sub

Private Sub Command67_Click()
DoCmd.OpenForm "frm_Log_Requests"
End Sub

Private Sub Command69_Click()
DoCmd.OpenForm "frm_Log_Meeting"
End Sub